angular.module('livrosApp',[
  'listagemLivro',
  'cadastroLivro',
  'cadastroUsuario',
  'telaLogin',
  'homeHeader',
  'homeFooter',
  'homeJumbotron',
  'cardLivro',
  'ngMaterial',
  'ngMessages'
]);
